{% set version = "1.033" %}

package:
  name: perl-test-output
  version: {{ version }}

source:
  url: https://github.com/briandfoy/test-output/archive/release-{{ version }}.tar.gz
  sha256: 35f0a4ef2449fc78886b4c99e1c1d23f432c2fae98538a4489439eb17223bfc2

build:
  number: 0
  script: perl Makefile.PL INSTALLDIRS=site && make && make test && make install
  skip: true  # [win]

requirements:
  host:
    - perl
    - perl-capture-tiny
  run:
    - perl
    - perl-capture-tiny

test:
  imports:
    - Test::Output

about:
  home: https://github.com/briandfoy/test-output
  license: Artistic-2.0
  license_file: LICENSE
  summary: Utilities to test STDOUT and STDERR messages
  doc_url: https://metacpan.org/pod/Test::Output

extra:
  recipe-maintainers:
    - '0xaf1f'
